using System;
using System.Collections.Generic;
using System.Text;

namespace UnityTools.Sheets.Editor
{
    public static class CsvCodeGenerator
    {
        //============================================================
        // Readonly
        //============================================================
        private static readonly HashSet<string> _keywords = new HashSet<string>("abstract as base bool break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long namespace new null object operator out override params private protected public readonly ref return sbyte sealed short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while __arglist __makeref __reftype __refvalue".Split(' '), StringComparer.Ordinal);

        //============================================================
        // Logic
        //============================================================
        public static bool TryGenerate(CsvTable table, IReadOnlyList<CsvColumn> columns, string namespaceName, string className, out string source, out string error)
        {
            source = null;
            error = string.Empty;
            if (table == null || columns == null || columns.Count != table.Headers.Count || columns.Count == 0)
            {
                error = "CSV와 모든 열의 타입 설정이 필요합니다.";
                return false;
            }

            if (!IsIdentifier(className) || className[0] < 'A' || className[0] > 'Z' || className == "CsvSourceRow" || className == "CsvCellValue" || className == "UnityTools")
            {
                error = "클래스 이름은 영문 대문자로 시작하는 유효한 C# 식별자여야 합니다.";
                return false;
            }

            if (string.IsNullOrEmpty(namespaceName))
            {
                error = "네임스페이스를 입력하세요.";
                return false;
            }

            string[] namespaces = namespaceName.Split('.');
            for (int idx = 0; idx < namespaces.Length; idx++)
            {
                if (!IsIdentifier(namespaces[idx]) || namespaces[idx] == "CsvSourceRow" || namespaces[idx] == "CsvCellValue")
                {
                    error = "네임스페이스의 각 이름은 유효한 C# 식별자여야 합니다.";
                    return false;
                }
            }

            HashSet<string> headers = new HashSet<string>(StringComparer.Ordinal);
            HashSet<string> names = new HashSet<string>(StringComparer.Ordinal);
            for (int idx = 0; idx < columns.Count; idx++)
            {
                CsvColumn column = columns[idx];
                if (column == null || !IsIdentifier(column.Name) || column.Name[0] < 'A' || column.Name[0] > 'Z' || column.Name == className || column.Name == "TryRead" || column.Name == "CsvSourceRow" || column.Name == "CsvCellValue" || !names.Add(column.Name))
                {
                    error = $"{idx + 1}열: Property 이름은 영문 대문자로 시작하며 중복되거나 클래스/메서드 이름과 같을 수 없습니다.";
                    return false;
                }

                if (column.Header == null || !ContainsHeader(table, column.Header) || !headers.Add(column.Header) || !Enum.IsDefined(typeof(ECsvColumnType), column.Type))
                {
                    error = $"{idx + 1}열: 헤더 연결 또는 타입 설정이 잘못되었습니다.";
                    return false;
                }

                if (column.Type == ECsvColumnType.Bool && !column.Name.StartsWith("Is", StringComparison.Ordinal) && !column.Name.StartsWith("Has", StringComparison.Ordinal) && !column.Name.StartsWith("Can", StringComparison.Ordinal) && !column.Name.StartsWith("Should", StringComparison.Ordinal))
                {
                    error = $"{idx + 1}열: bool Property 이름은 Is, Has, Can, Should로 시작해야 합니다.";
                    return false;
                }

                for (int rowIdx = 0; rowIdx < table.Rows.Count; rowIdx++)
                {
                    CsvRow row = table.Rows[rowIdx];
                    if (!row.TryGetCell(column.Header, out string text) || !IsValueValid(text, column.Type))
                    {
                        error = $"{row.LineNum}행, '{column.Header}'열: {column.Type} 값이 올바르지 않습니다.";
                        return false;
                    }
                }
            }

            StringBuilder code = new StringBuilder();
            code.AppendLine("// Generated by UnityTools Sheets. Regenerate after changing the schema.");
            code.AppendLine("using CsvSourceRow = UnityTools.Sheets.CsvRow;");
            code.AppendLine("using CsvCellValue = UnityTools.Sheets.CsvValue;");
            code.AppendLine();
            code.AppendLine("namespace " + namespaceName);
            code.AppendLine("{");
            code.AppendLine("    public class " + className);
            code.AppendLine("    {");
            AppendSection(code, "Readonly");
            for (int idx = 0; idx < columns.Count; idx++)
            {
                CsvColumn column = columns[idx];
                code.AppendLine("        private readonly " + TypeName(column.Type) + " _" + char.ToLowerInvariant(column.Name[0]) + column.Name.Substring(1) + ";");
            }

            AppendSection(code, "Properties");
            for (int idx = 0; idx < columns.Count; idx++)
            {
                CsvColumn column = columns[idx];
                code.AppendLine("        public " + TypeName(column.Type) + " " + column.Name + " => _" + char.ToLowerInvariant(column.Name[0]) + column.Name.Substring(1) + ";");
            }

            AppendSection(code, "Constructors");
            List<string> parameters = new List<string>();
            for (int idx = 0; idx < columns.Count; idx++)
            {
                parameters.Add(TypeName(columns[idx].Type) + " value" + idx);
            }

            code.AppendLine("        private " + className + "(" + string.Join(", ", parameters) + ")");
            code.AppendLine("        {");
            for (int idx = 0; idx < columns.Count; idx++)
            {
                string name = columns[idx].Name;
                code.AppendLine("            _" + char.ToLowerInvariant(name[0]) + name.Substring(1) + " = value" + idx + ";");
            }

            code.AppendLine("        }");
            AppendSection(code, "Logic");
            code.AppendLine("        public static bool TryRead(CsvSourceRow row, out " + className + " data, out string error)");
            code.AppendLine("        {");
            code.AppendLine("            data = null;");
            code.AppendLine("            error = string.Empty;");
            code.AppendLine("            if (row == null)");
            code.AppendLine("            {");
            code.AppendLine("                error = \"CSV 행이 없습니다.\";");
            code.AppendLine("                return false;");
            code.AppendLine("            }");
            List<string> arguments = new List<string>();
            for (int idx = 0; idx < columns.Count; idx++)
            {
                CsvColumn column = columns[idx];
                code.AppendLine();
                string condition = "!row.TryGetCell(" + Literal(column.Header) + ", out string raw" + idx + ")";
                if (column.Type != ECsvColumnType.String)
                    condition += " || !CsvCellValue.TryParse(raw" + idx + ", out " + TypeName(column.Type) + " value" + idx + ")";

                code.AppendLine("            if (" + condition + ")");
                code.AppendLine("            {");
                code.AppendLine("                error = row.LineNum + " + Literal("행, '" + column.Header + "'열: " + column.Type + " 값을 읽을 수 없습니다.") + ";");
                code.AppendLine("                return false;");
                code.AppendLine("            }");
                arguments.Add((column.Type == ECsvColumnType.String ? "raw" : "value") + idx);
            }

            code.AppendLine();
            code.AppendLine("            data = new " + className + "(" + string.Join(", ", arguments) + ");");
            code.AppendLine("            return true;");
            code.AppendLine("        }");
            code.AppendLine("    }");
            code.AppendLine("}");
            source = code.ToString();
            return true;
        }

        //============================================================
        // Utilities
        //============================================================
        private static bool IsIdentifier(string value)
        {
            if (string.IsNullOrEmpty(value) || _keywords.Contains(value))
                return false;

            for (int idx = 0; idx < value.Length; idx++)
            {
                char ch = value[idx];
                bool isLetter = ch >= 'a' && ch <= 'z' || ch >= 'A' && ch <= 'Z';
                if (!isLetter && ch != '_' && (idx == 0 || ch < '0' || ch > '9'))
                    return false;
            }

            return true;
        }

        private static bool ContainsHeader(CsvTable table, string header)
        {
            for (int idx = 0; idx < table.Headers.Count; idx++)
            {
                if (table.Headers[idx] == header)
                    return true;
            }

            return false;
        }

        private static bool IsValueValid(string text, ECsvColumnType type)
        {
            switch (type)
            {
                case ECsvColumnType.Int: return CsvValue.TryParse(text, out int intValue);
                case ECsvColumnType.Long: return CsvValue.TryParse(text, out long longValue);
                case ECsvColumnType.Float: return CsvValue.TryParse(text, out float floatValue);
                case ECsvColumnType.Double: return CsvValue.TryParse(text, out double doubleValue);
                case ECsvColumnType.Bool: return CsvValue.TryParse(text, out bool boolValue);
                default: return true;
            }
        }

        private static string TypeName(ECsvColumnType type)
        {
            return type.ToString().ToLowerInvariant();
        }

        private static string Literal(string value)
        {
            StringBuilder text = new StringBuilder("\"");
            for (int idx = 0; idx < value.Length; idx++)
            {
                char ch = value[idx];
                if (ch == '\\' || ch == '"')
                {
                    text.Append('\\').Append(ch);
                }
                else if (char.IsControl(ch) || ch == '\u2028' || ch == '\u2029')
                {
                    text.Append("\\u").Append(((int)ch).ToString("x4"));
                }
                else
                {
                    text.Append(ch);
                }
            }

            return text.Append('"').ToString();
        }

        private static void AppendSection(StringBuilder code, string name)
        {
            code.AppendLine();
            code.AppendLine("        //============================================================");
            code.AppendLine("        // " + name);
            code.AppendLine("        //============================================================");
        }
    }
}
