using System;
using System.Collections.Generic;
using System.Text;

namespace UnityTools.Sheets.Editor
{
    public static class CsvCodeGenerator
    {
        //============================================================
        // Readonly
        //============================================================
        private static readonly HashSet<string> _keywords = new HashSet<string>("abstract as base bool break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long namespace new null object operator out override params private protected public readonly ref return sbyte sealed short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while __arglist __makeref __reftype __refvalue".Split(' '), StringComparer.Ordinal);

        //============================================================
        // Logic
        //============================================================
        public static bool TryGenerate(CsvTable table, IReadOnlyList<CsvColumn> columns, string namespaceName, string className, out string source, out string error)
        {
            source = null;
            error = string.Empty;
            IReadOnlyList<CsvValidationIssue> issues = Validate(table, columns, namespaceName, className);
            if (issues.Count > 0)
            {
                error = issues[0].Message;
                return false;
            }

            StringBuilder code = new StringBuilder();
            code.AppendLine("// Generated by UnityTools Sheets. Regenerate after changing the schema.");
            code.AppendLine("using CsvSourceRow = UnityTools.Sheets.CsvRow;");
            code.AppendLine("using CsvCellValue = UnityTools.Sheets.CsvValue;");
            for (int idx = 0; idx < columns.Count; idx++)
            {
                if (columns[idx].Type == ECsvColumnType.Enum)
                {
                    if (!columns[idx].IsArray)
                        code.AppendLine("using CsvEnumType" + idx + " = " + columns[idx].EnumType.FullName + ";");

                    code.AppendLine("using CsvEnumReader" + idx + " = UnityTools.Sheets.CsvEnum<" + columns[idx].EnumType.FullName + ">;");
                }

                if (columns[idx].IsArray)
                {
                    string elementType = columns[idx].Type == ECsvColumnType.Enum ? columns[idx].EnumType.FullName : columns[idx].Type.ToString().ToLowerInvariant();
                    code.AppendLine("using CsvArrayType" + idx + " = System.Collections.Generic.IReadOnlyList<" + elementType + ">;");
                    code.AppendLine("using CsvArrayReader" + idx + " = UnityTools.Sheets.CsvArray<" + elementType + ">;");
                }
            }
            code.AppendLine();
            code.AppendLine("namespace " + namespaceName);
            code.AppendLine("{");
            code.AppendLine("    public class " + className);
            code.AppendLine("    {");
            AppendSection(code, "Readonly");
            for (int idx = 0; idx < columns.Count; idx++)
            {
                CsvColumn column = columns[idx];
                code.AppendLine("        private readonly " + TypeName(column, idx) + " _" + char.ToLowerInvariant(column.Name[0]) + column.Name.Substring(1) + ";");
            }

            AppendSection(code, "Properties");
            for (int idx = 0; idx < columns.Count; idx++)
            {
                CsvColumn column = columns[idx];
                code.AppendLine("        public " + TypeName(column, idx) + " " + column.Name + " => _" + char.ToLowerInvariant(column.Name[0]) + column.Name.Substring(1) + ";");
            }

            AppendSection(code, "Constructors");
            List<string> parameters = new List<string>();
            for (int idx = 0; idx < columns.Count; idx++)
            {
                parameters.Add(TypeName(columns[idx], idx) + " value" + idx);
            }

            code.AppendLine("        private " + className + "(" + string.Join(", ", parameters) + ")");
            code.AppendLine("        {");
            for (int idx = 0; idx < columns.Count; idx++)
            {
                string name = columns[idx].Name;
                code.AppendLine("            _" + char.ToLowerInvariant(name[0]) + name.Substring(1) + " = value" + idx + ";");
            }

            code.AppendLine("        }");
            AppendSection(code, "Logic");
            code.AppendLine("        public static bool TryRead(CsvSourceRow row, out " + className + " data, out string error)");
            code.AppendLine("        {");
            code.AppendLine("            data = null;");
            code.AppendLine("            error = string.Empty;");
            code.AppendLine("            if (row == null)");
            code.AppendLine("            {");
            code.AppendLine("                error = \"CSV 행이 없습니다.\";");
            code.AppendLine("                return false;");
            code.AppendLine("            }");
            List<string> arguments = new List<string>();
            for (int idx = 0; idx < columns.Count; idx++)
            {
                CsvColumn column = columns[idx];
                code.AppendLine();
                string condition = "!row.TryGetCell(" + Literal(column.Header) + ", out string raw" + idx + ")";
                if (column.IsArray)
                {
                    string reader = column.Type == ECsvColumnType.Enum ? "CsvEnumReader" + idx + ".TryParse" : "CsvCellValue.TryParse";
                    condition += " || !CsvArrayReader" + idx + ".TryParse(raw" + idx + ", " + reader + ", out " + TypeName(column, idx) + " value" + idx + ")";
                }
                else if (column.Type == ECsvColumnType.Enum)
                {
                    condition += " || !CsvEnumReader" + idx + ".TryParse(raw" + idx + ", out " + TypeName(column, idx) + " value" + idx + ")";
                }
                else if (column.Type != ECsvColumnType.String)
                {
                    condition += " || !CsvCellValue.TryParse(raw" + idx + ", out " + TypeName(column, idx) + " value" + idx + ")";
                }

                code.AppendLine("            if (" + condition + ")");
                code.AppendLine("            {");
                code.AppendLine("                error = row.LineNum + " + Literal("행, '" + column.Header + "'열: " + column.Type + " 값을 읽을 수 없습니다.") + ";");
                code.AppendLine("                return false;");
                code.AppendLine("            }");
                arguments.Add((column.Type == ECsvColumnType.String && !column.IsArray ? "raw" : "value") + idx);
            }

            code.AppendLine();
            code.AppendLine("            data = new " + className + "(" + string.Join(", ", arguments) + ");");
            code.AppendLine("            return true;");
            code.AppendLine("        }");
            code.AppendLine("    }");
            code.AppendLine("}");
            source = code.ToString();
            return true;
        }

        public static IReadOnlyList<CsvValidationIssue> Validate(CsvTable table, IReadOnlyList<CsvColumn> columns, string namespaceName, string className)
        {
            List<CsvValidationIssue> issues = new List<CsvValidationIssue>();
            if (!TryValidateSchema(table, columns, namespaceName, className, out string error))
            {
                issues.Add(new CsvValidationIssue(0, string.Empty, error));
                return issues.AsReadOnly();
            }

            for (int idx = 0; idx < columns.Count; idx++)
            {
                CsvColumn column = columns[idx];
                string[] enumNames = column.Type == ECsvColumnType.Enum ? Enum.GetNames(column.EnumType) : null;
                for (int rowIdx = 0; rowIdx < table.Rows.Count; rowIdx++)
                {
                    CsvRow row = table.Rows[rowIdx];
                    if (!row.TryGetCell(column.Header, out string text) || !IsCellValid(text, column, enumNames))
                        issues.Add(new CsvValidationIssue(row.LineNum, column.Header, $"{row.LineNum}행, '{column.Header}'열: {column.Type} 값이 올바르지 않습니다."));
                }
            }

            return issues.AsReadOnly();
        }

        private static bool TryValidateSchema(CsvTable table, IReadOnlyList<CsvColumn> columns, string namespaceName, string className, out string error)
        {
            error = string.Empty;
            if (table == null || columns == null || columns.Count != table.Headers.Count || columns.Count == 0)
            {
                error = "CSV와 모든 열의 타입 설정이 필요합니다.";
                return false;
            }

            if (!IsIdentifier(className) || className[0] < 'A' || className[0] > 'Z' || className == "CsvSourceRow" || className == "CsvCellValue" || className == "UnityTools")
            {
                error = "클래스 이름은 영문 대문자로 시작하는 유효한 C# 식별자여야 합니다.";
                return false;
            }

            if (string.IsNullOrEmpty(namespaceName))
            {
                error = "네임스페이스를 입력하세요.";
                return false;
            }

            string[] namespaces = namespaceName.Split('.');
            for (int idx = 0; idx < namespaces.Length; idx++)
            {
                if (!IsIdentifier(namespaces[idx]) || namespaces[idx] == "CsvSourceRow" || namespaces[idx] == "CsvCellValue")
                {
                    error = "네임스페이스의 각 이름은 유효한 C# 식별자여야 합니다.";
                    return false;
                }
            }

            HashSet<string> headers = new HashSet<string>(StringComparer.Ordinal);
            HashSet<string> names = new HashSet<string>(StringComparer.Ordinal);
            for (int idx = 0; idx < columns.Count; idx++)
            {
                CsvColumn column = columns[idx];
                if (column == null || !IsIdentifier(column.Name) || column.Name[0] < 'A' || column.Name[0] > 'Z' || column.Name == className || column.Name == "TryRead" || column.Name == "CsvSourceRow" || column.Name == "CsvCellValue" || !names.Add(column.Name))
                {
                    error = $"{idx + 1}열: Property 이름은 영문 대문자로 시작하며 중복되거나 클래스/메서드 이름과 같을 수 없습니다.";
                    return false;
                }

                if (column.Header == null || !ContainsHeader(table, column.Header) || !headers.Add(column.Header) || !Enum.IsDefined(typeof(ECsvColumnType), column.Type))
                {
                    error = $"{idx + 1}열: 헤더 연결 또는 타입 설정이 잘못되었습니다.";
                    return false;
                }

                if (column.Type == ECsvColumnType.Bool && !column.IsArray && !column.Name.StartsWith("Is", StringComparison.Ordinal) && !column.Name.StartsWith("Has", StringComparison.Ordinal) && !column.Name.StartsWith("Can", StringComparison.Ordinal) && !column.Name.StartsWith("Should", StringComparison.Ordinal))
                {
                    error = $"{idx + 1}열: bool Property 이름은 Is, Has, Can, Should로 시작해야 합니다.";
                    return false;
                }

                if (column.Type == ECsvColumnType.Enum && !IsEnumSupported(column.EnumType))
                {
                    error = $"{idx + 1}열: Player에서 참조 가능한 public top-level enum 타입이 필요합니다.";
                    return false;
                }
            }

            return true;
        }

        //============================================================
        // Utilities
        //============================================================
        private static bool IsIdentifier(string value)
        {
            if (string.IsNullOrEmpty(value) || _keywords.Contains(value) || value.StartsWith("CsvEnumType", StringComparison.Ordinal) || value.StartsWith("CsvEnumReader", StringComparison.Ordinal) || value.StartsWith("CsvArrayType", StringComparison.Ordinal) || value.StartsWith("CsvArrayReader", StringComparison.Ordinal))
                return false;

            for (int idx = 0; idx < value.Length; idx++)
            {
                char ch = value[idx];
                bool isLetter = ch >= 'a' && ch <= 'z' || ch >= 'A' && ch <= 'Z';
                if (!isLetter && ch != '_' && (idx == 0 || ch < '0' || ch > '9'))
                    return false;
            }

            return true;
        }

        private static bool ContainsHeader(CsvTable table, string header)
        {
            for (int idx = 0; idx < table.Headers.Count; idx++)
            {
                if (table.Headers[idx] == header)
                    return true;
            }

            return false;
        }

        private static bool IsValueValid(string text, ECsvColumnType type)
        {
            switch (type)
            {
                case ECsvColumnType.Int: return CsvValue.TryParse(text, out int intValue);
                case ECsvColumnType.Long: return CsvValue.TryParse(text, out long longValue);
                case ECsvColumnType.Float: return CsvValue.TryParse(text, out float floatValue);
                case ECsvColumnType.Double: return CsvValue.TryParse(text, out double doubleValue);
                case ECsvColumnType.Bool: return CsvValue.TryParse(text, out bool boolValue);
                default: return true;
            }
        }

        private static bool IsCellValid(string text, CsvColumn column, string[] enumNames)
        {
            if (!column.IsArray)
                return enumNames != null ? Array.IndexOf(enumNames, text) >= 0 : IsValueValid(text, column.Type);

            if (text == null)
                return false;

            if (text.Length == 0)
                return true;

            string[] cells = text.Split('|');
            for (int idx = 0; idx < cells.Length; idx++)
            {
                if (cells[idx].Length == 0 || (enumNames != null ? Array.IndexOf(enumNames, cells[idx]) < 0 : !IsValueValid(cells[idx], column.Type)))
                    return false;
            }

            return true;
        }

        private static bool IsEnumSupported(Type type)
        {
            if (type == null || !type.IsEnum || !type.IsPublic || type.IsNested || type.ContainsGenericParameters)
                return false;

            string[] parts = type.FullName.Split('.');
            for (int idx = 0; idx < parts.Length; idx++)
            {
                if (!IsIdentifier(parts[idx]))
                    return false;
            }

            UnityEditor.Compilation.Assembly[] assemblies = UnityEditor.Compilation.CompilationPipeline.GetAssemblies(UnityEditor.Compilation.AssembliesType.Editor);
            string assemblyName = type.Assembly.GetName().Name;
            for (int idx = 0; idx < assemblies.Length; idx++)
            {
                if (assemblies[idx].name == assemblyName)
                    return (assemblies[idx].flags & UnityEditor.Compilation.AssemblyFlags.EditorAssembly) == 0;
            }

            return type.Assembly == typeof(DayOfWeek).Assembly;
        }

        private static string TypeName(CsvColumn column, int idx)
        {
            if (column.IsArray)
                return "CsvArrayType" + idx;

            return column.Type == ECsvColumnType.Enum ? "CsvEnumType" + idx : column.Type.ToString().ToLowerInvariant();
        }

        private static string Literal(string value)
        {
            StringBuilder text = new StringBuilder("\"");
            for (int idx = 0; idx < value.Length; idx++)
            {
                char ch = value[idx];
                if (ch == '\\' || ch == '"')
                {
                    text.Append('\\').Append(ch);
                }
                else if (char.IsControl(ch) || ch == '\u2028' || ch == '\u2029')
                {
                    text.Append("\\u").Append(((int)ch).ToString("x4"));
                }
                else
                {
                    text.Append(ch);
                }
            }

            return text.Append('"').ToString();
        }

        private static void AppendSection(StringBuilder code, string name)
        {
            code.AppendLine();
            code.AppendLine("        //============================================================");
            code.AppendLine("        // " + name);
            code.AppendLine("        //============================================================");
        }
    }
}
